
%ifndef keys
%define keys

%define key.up    		0x48
%define key.down  		0x50
%define key.left  		0x4b
%define key.right 		0x4d
%define key.enter 		0x1c
%define key.esc   		0x01
%define key.bcksp 		0x0e
%define key.tab   		0x0f
%define key.ctrl  		0x1d
%define key.quotes 		0x28
%define key.aprox 		0x29
%define key.leftshf 	0x2a
%define key.rightshf 	0x36
%define key.prtscr 		0x37
%define key.alt   		0x38
%define key.spc   		0x39
%define key.capslock 	0x3a
%endif ; keyboard_mac
