
%ifndef keys
%define keys

%define key.up    		0x48
%define key.down  		0x50
%define key.left  		0x4b
%define key.right 		0x4d
%define key.enter 		0x1c
%define key.esc   		0x01
%define key.backspace 	0x0e
%define key.tab   		0x0f
%define key.ctrl  		0x9d1d
%define key.shiftL 		0xaa2a
%define key.shiftR	 	0xb636
%define key.alt   		0xb838
%define key.space   	0x39
%define key.capslock 	0xba3a
%endif ; keyboard_mac